env:
    browser: true
    es2021: true
extends:
    [
        airbnb-base,
        plugin:react-hooks/recommended,
        plugin:import/recommended,
        prettier,
    ]
overrides: []
parserOptions:
    ecmaVersion: latest
    sourceType: module
rules: {}
